name: Release

on:
  release:
    types: [ created ]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create zip of repository
      run: |
        $zipName = "windows-auto-updater-$($env:GITHUB_REF_NAME).zip"
        $out = Join-Path $env:GITHUB_WORKSPACE $zipName
        Compress-Archive -Path * -DestinationPath $out -Force
        Write-Output "::set-output name=zip::$out"
      shell: pwsh

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: "windows-auto-updater-$GITHUB_REF_NAME.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
